### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by katz0018** [nilababaei/portfolio#1]
| | 0 points | 1 points | 2 points | **3 points** |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use **|
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics **|

DUDE! Your code makes the website super smooth and satisfying to use. The message that you want to do coding is very evident. Very well executed!!!! I also loveee the color palette <3 A++++++

**Comment by nilababaei** [comment]
Thank you <3
