### ISSUE TITLE
Pattern Library Critique

### ISSUE THREAD

**Issue by megan-smith-6** [nilababaei/portfolio#2]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Patterns** | Barely started | Missing lots of patterns | Has most of the patterns, some missing | **All patterns exist and are well done** |
| **Personality** | Bland, boring, just another graphic designer | Fairly generic but may be better with visual design | Quality layouts and unique, personable content | **Unique and recognizable as you, with engaging, personable content** |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | **Looks great on all screen sizes** |
| **Documentation** | No documentation | Very little documentation | Mostly well documented | **Amazing! Anybody could understand** |
| **Use of systems** | Everything is repeated | Some good use of Jekyll & Patternbot | Lots of good systemization & reuse | **Lego!** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

**There are a few small things I would suggest for your pattern library.**
• Perhaps remove your card unless you decide you will be using it on its own.
• For the dropdown in your header, it closes on its own, but only when your mouse is on the bottom half of the screen.
• Lastly, for your Default Text Section and Project Info Section, the title breaks and the bottom h1 tag doesn't match up with the alignment of the first one. I am not sure if you can fix it or not, but it's just a minor thing.

Overall, everything is looking good!

**Comment by nilababaei** [comment]
Thank you so much for the feedback! I will make sure to implement those changes :)
