### ISSUE TITLE
Pattern-Library Critique

### ISSUE THREAD

**Issue by alexhealy** [nilababaei/portfolio#5]
@thomasjbradley

| 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | This pattern library has a great use of creativeness along with the clean and colour coordinated sections. I think the "coding" theme was portrayed really well through the design, especially seen in the logo. |
| **Effectiveness** | The project is super effective and easy to use. Everything is labeled and the descriptions for each section and are easy to understand. |
| **Quality** | Stunning quality, everything looks very clean and put together. The flow works very well |
| **Effort** | Amazing, over-the-top amount of effort. Everything is very easy to use and understand  |
| **Code quality** | Well indented, fully valid, good use of semantics. Everything works well, the hover effects look great on the cards. |

**Comment by nilababaei** [comment]
Thank you for the feedback!
