### ISSUE TITLE
Portfolio Peer Evaluation

### ISSUE THREAD

**Issue by fkhan24** [nilababaei/portfolio#8]
Your website is amazing! Every page is organized and the layout is clean and visually appealing. I really like your use of colours and how you set a theme for every portfolio piece based on the colours used in the web design. Your cards are neat and responsive, as well as your header and hamburger nav. I really like your use of tabbed interfaces and how you've separated the detail of your case study within them. It really helps organize your content into small sections and makes it interactive. Lastly, I loved how you incorporated your HTML tags into your design layout and your overall website really shows your skills as a successful web developer. Good work!

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** |
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

**Comment by nilababaei** [comment]
Thank you so much!
